### ISSUE TITLE
Improving the accuracy

### ISSUE THREAD

**Issue by ChillarAnand** [GayamTrishal/OCR_Telugu_code#4]
I am trying to run this ocr on a [simple dataset](https://github.com/ChillarAnand/likitham/tree/master/dataset/test_images) and the accuracy seems low. Are there any specifications for the input images? How can the accuracy improved on images like this?

**Comment by chandu-97** [comment]
Rescale the character images to standard size. Then rotations, translations, deformations and rescaling to increase dataset size. You can even try a smaller CNN.
